# exercicios 2, 3, e 4

version: '3'

services:
  ghost-blog:
    container_name: ghost-blog
    image: ghost:1-alpine
    ports: 
      - 2368:2368
    environment:
       - database__client=mysql
       - database__connection__host=mysql
       - database__connection__user=root
       - database__connection__password=root
       - database__connection__database=ghost
      #  - database__connection__port=3306
    depends_on:
      - "mysql"
    networks:
      - my-network
    restart: always

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "db_data:/var/lib/mysql"
    networks:
      - my-network
    restart: always

volumes:
  db_data:

networks:
  my-network:
