SELECT 'This is SQL Exercise, Practice and Solution';
SELECT 1, 2, 3;
SELECT 10 + 5;
SELECT 612 * 34;
SELECT * FROM Scientists;
SELECT Name AS 'Nomde do Projeto', Hours AS 'Tempo de Trabalho' FROM Scientists.Projects;
SELECT Name FROM Scientists.Scientists ORDER BY Name;
SELECT Name FROM Scientists.Projects ORDER BY Name DESC;
SELECT CONCAT('O projeto ', Name, ' precisou de ', Hours, ' horas para ser concluído.') as resultado FROM Scientists.Projects;
SELECT Name, Hours FROM Scientists.Projects ORDER BY Hours DESC LIMIT 3;
SELECT DISTINCT Project FROM Scientists.AssignedTo;
SELECT Name FROM Scientists.Projects ORDER BY Hours DESC LIMIT 1;
SELECT Name FROM Scientists.Projects ORDER BY Hours LIMIT 1 OFFSET 1;
SELECT * FROM Scientists.Projects ORDER BY Hours LIMIT 5;
SELECT CONCAT('Exitem ', COUNT(Name), ' cientistas na tabela Scientists.') FROM Scientists.Scientists;